# Generated by Django 6.0.3 on 2026-03-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_purchaseorderitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("sale_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
